### ISSUE TITLE
vsphere_cspec_list and vsphere_cspec_query feedback request

### ISSUE THREAD

**Issue by kbrowns** [chef-partners/knife-vsphere#196] opened 2015-09-02 13:45 UTC
I wanted to get some feedback on this idea before going down this path.  My team is using customization specifications rather heavily, and currently they are created and stored on vsphere via the GUI and referenced by name in our knife-vsphere commands.  We would like to start moving those into code so that those infrastructure details are codified in code along with everything else we're doing.  I've struggled a bit trying to figure out how to do this "porting" effectively.  I'm seeing a pretty robust API in rbvmomi that appears to allow for doing all of this programmatically and in the clone command there's code that's querying for the cspec - i.e.:

```
      csi = find_customization(get_config(:customization_spec)) ||
            fatal_exit("failed to find customization specification named #{get_config(:customization_spec)}")

      cust_spec = csi.spec

  def find_customization(name)
    csm = config[:vim].serviceContent.customizationSpecManager
    csm.GetCustomizationSpec(name: name)
  end
```

I've been adding logging statements to dump out the spec's object state so that I can see it and start porting it.  Would anyone else like to see this added as a first class command?  Such as:

```
knife vsphere cspec list
```

which would print out all customization specifications in a named list. and then something like:

```
knife vsphere cspec query <cspec-name>
```

which would do the above look up and "p" out the object state?  Below is an example of the latter which that I've captured from the aforementioned logging I've added:

```
#<RbVmomi::VIM::CustomizationSpec:0x41f9e20 @props= {
     :options=> #<RbVmomi::VIM::CustomizationWinOptions:0x417ceb8 @props= {
          :changeSID=>true,
          :deleteAccounts=>false
     }>,

     :identity=>#<RbVmomi::VIM::CustomizationSysprep:0x416a9d8 @props= {

          :guiUnattended=>#<RbVmomi::VIM::CustomizationGuiUnattended:0x4161e88 @props= {
               :password=>#<RbVmomi::VIM::CustomizationPassword:0x414e868 @props= {
                    :value=>"--snipped-encrypted-text---",
                    :plainText=>false
               }>,
               :timeZone=>25,
               :autoLogon=>false,
               :autoLogonCount=>1
          }>,

          :userData=>#<RbVmomi::VIM::CustomizationUserData:0x412c1a0 @props= {
               :fullName=>"CSG",
               :orgName=>"CSG International",
               :computerName=>#<RbVmomi::VIM::CustomizationVirtualMachineName:0x4114488 @props= {
               }>,
               :productId=>"--snip--"
          }>,

          :identification=>#<RbVmomi::VIM::CustomizationIdentification:0x410c8c8 @props= {
               :joinWorkgroup=>"WORKGROUP"
          }>,

          :licenseFilePrintData=>#<RbVmomi::VIM::CustomizationLicenseFilePrintData:0x40f78e0 @props= {
               :autoMode=>"perServer",
               :autoUsers=>5
          }>
     }>,
     :globalIPSettings=>#<RbVmomi::VIM::CustomizationGlobalIPSettings:0x40c6ab8 @props= {
          :dnsSuffixList=>[],
          :dnsServerList=>[]
     }>,
     :nicSettingMap=>
     [
          #<RbVmomi::VIM::CustomizationAdapterMapping:0x40bfdf8 @props= {
               :adapter=>#<RbVmomi::VIM::CustomizationIPSettings:0x40b5790 @props= {
                    :ip=>#<RbVmomi::VIM::CustomizationDhcpIpGenerator:0x40ad918 @props= {
                    }>,
                    :gateway=>[],
                    :dnsServerList=>[]
               }
          >}>
     ],
     :encryptionKey=>[--snip--]
}>
```

This has been invaluable for my team trying to figure out how to port these things in vsphere to code.

**Comment by swalberg** [comment] 2015-09-02 14:53
That's a great idea. We don't use cspecs that heavily here but I can see how that would be helpful for those that do. And while there's no established vision for this plugin by the original authors, I've been taking the approach that anything you can do in the VSphere console is fair game for this plugin.

I think that as a first pass, `pp`'ing the structure is good, too.

The only suggestion I'd make to this is to use `show` instead of `query`, so that we're consistent with the rest of the `knife` commands (I see that both `vsphere pool` and `vsphere vm` support `query`, and when I get a moment I'll get it to support both)

**Comment by swalberg** [comment] 2018-04-02 00:26
Hi, did you get anywhere on this? I was talking to my coworkers about this last week and didn't know someone had already done some thinking on it.

I realize the issue is over 2 years old so I'll close it as part of some cleanup I'm doing, but please do re-open if you're still around.

**Closed by swalberg** 2018-04-02 00:26 UTC
Labels: Enhancement

**Comment by kbrowns** [comment] 2018-04-09 19:11
Sean - we never got around to it.  We decided to steer clear of cspecs, and since then we've moved entirely to EC2 for new work and vRA for the remaining legacy stuff.  I haven't touched VMWare in a very long time.  Good luck
