### ISSUE TITLE
clone fails - No host specified

### ISSUE THREAD

**Issue by arctouch-shadowroldan** [chef-partners/knife-vsphere#2] opened 2011-09-23 20:25 UTC
On Mac OS X using ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

When attempting to clone:

sroldan$ knife vsphere vm clone d-test01 PersonalDev -VV
Cloning template PersonalDev to new VM d-test01
/Library/Ruby/Gems/1.8/gems/rbvmomi-1.2.3/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion': InvalidArgument: A specified parameter was not correct.  (RbVmomi::Fault)
host
	from /Library/Ruby/Gems/1.8/gems/knife-vsphere-0.1.5/lib/chef/knife/vsphere_vm_clone.rb:123:in `run'
	from /Library/Ruby/Gems/1.8/gems/chef-0.10.4/lib/chef/knife.rb:391:in `run_with_pretty_exceptions'
	from /Library/Ruby/Gems/1.8/gems/chef-0.10.4/lib/chef/knife.rb:166:in `run'
	from /Library/Ruby/Gems/1.8/gems/chef-0.10.4/lib/chef/application/knife.rb:128:in `run'
	from /Library/Ruby/Gems/1.8/gems/chef-0.10.4/bin/knife:25
	from /usr/bin/knife:19:in `load'
	from /usr/bin/knife:19

**Comment by DennisBP** [comment] 2015-04-21 11:02
Does the problem still exist or can we close the bug report?

**Comment by atiniir** [comment] 2015-05-07 19:14
it still exists. i'm trying to get through it right now 

i'd be SUPER thrilled to test anything or provide whatever information you guys want

**Comment by swalberg** [comment] 2015-05-07 20:21
Still running ESX 4.1? And you're running `knife vsphere vm clone ks-chef04 --template LAB_WIN7_x64` ?

https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L271-L273 is where the task gets set up and executed. Best I can think of right now is adding some debugging around Line 271 (`C:/Users/kstewart/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.0.1/lib/chef/knife/vsphere_vm_clone.rb`) such as

```ruby
puts "Dumping the task info"
puts dest_folder.inspect
puts clone_spec.inspect
```

**Comment by atiniir** [comment] 2015-05-07 21:00
VMware ESXi, 5.5.0, 2456374
 
The command line is knife vsphere vm clone ks-chef04 --template LAB_WIN7_x64 --cspec 'ITLAB Clone'   i discovered earlier that windows requires the cspec

I've also tried variations including supplying chost, cdomain, datastore, and dest-folder just for giggles 

I've dumped the inspects to files but it's an obscene amount of data (like 2 and 5 MB respectively).  How would you let me to share that? or was there a particular value/object/property you are interested in?

**Comment by swalberg** [comment] 2015-05-08 13:04
Ugh, sorry, I was hoping it would be something small, or better yet, a `nil` :)

Vsphere isn't being too helpful with its error message. Does it work with a Linux VM?

I was playing around a bit, and you can get saner debugging output with

```
puts "Dumping the task info"
pp dest_folder
pp clone_spec
```

**Comment by atiniir** [comment] 2015-05-14 01:44
Hey, sorry i should be able to try this out tomorrow and let you know.

**Comment by atiniir** [comment] 2015-05-15 23:57
ok so dest folder looks good, it's the folder ID 
    Dumping dest_folder
    Folder("group-v22")

the clone_spec dumps out a whole lot of info, i've trimmed out the encryption key and some of the other key values 

Dumping clone_spec
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    dynamicProperty: [],
    encryptionKey: [ROUGHLY 2775 Numbers],
    globalIPSettings: CustomizationGlobalIPSettings(
      dnsServerList: [],
      dnsSuffixList: [],
      dynamicProperty: []
    ),
    identity: CustomizationSysprep(
      dynamicProperty: [],
      guiUnattended: CustomizationGuiUnattended(
        autoLogon: true,
        autoLogonCount: 1,
        dynamicProperty: [],
        password: CustomizationPassword(
          dynamicProperty: [],
          plainText: false,
          value: "KEY VALUE"
        ),
        timeZone: 4
      ),
      identification: CustomizationIdentification(
        domainAdmin: "vmwareuser@itlab.company.com",
        domainAdminPassword: CustomizationPassword(
          dynamicProperty: [],
          plainText: false,
          value: "KEY VALUE"
        ),
        dynamicProperty: [],
        joinDomain: "itlab.company.com"
      ),
      licenseFilePrintData: CustomizationLicenseFilePrintData(
        autoMode: "perSeat",
        dynamicProperty: []
      ),
      userData: CustomizationUserData(
        computerName: CustomizationFixedName( name: "ks-chef04" ),
        dynamicProperty: [],
        fullName: "Company IT",
        orgName: "Company",
        productId: ""
      )
    ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings(
         dnsServerList: ["10.9.178.21", "10.9.178.22"],
         dynamicProperty: [],
         gateway: [],
         ip: CustomizationDhcpIpGenerator( dynamicProperty: [] ),
         primaryWINS: "",
         secondaryWINS: ""
       ),
       dynamicProperty: []
     )],
    options: CustomizationWinOptions(
      changeSID: true,
      deleteAccounts: false,
      dynamicProperty: []
    )
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-163"),
    pool: ResourcePool("resgroup-1102")
  ),
  powerOn: false,
  template: false
)

**Comment by swalberg** [comment] 2015-05-16 00:48
Thanks. I formatted your comment to make it a bit easier to read. I didn't realize the customization specs were so large for Windows!

I probably should have asked this earlier, but are there any logs coming from the VMWare side of things?

What seems to be happening here is that we're sending VMWare that big list of instructions to build a box and it's coming back saying "one of those is incorrect" without being specific.

When you have "KEY VALUE" written, was that literally what came out? Or did you replace an encrypted string?

I took a spot check of some of the data structures (just google for some of the names, like `CustomizationIPSettings`) to see if there was anything obvious missing. So far the only interesting thing is that `CustomizationUserData` expects a `ProductId` as a string and this is empty. I'm not sure if you have a product id to use, but that's just a guess. See http://pubs.vmware.com/vi30/sdk/ReferenceGuide/vim.vm.customization.UserData.html for more info on that field.

I'll continue to look... I'm also in Canada so it's a long weekend, not sure how much time I'll have.

**Comment by atiniir** [comment] 2015-05-19 17:20
I replaced the encrypted string mostly to keep it shorter. 

I'm in canada too, thus my Tuesday reply :) 

I'm getting the same error with a linux template i'll do a run of that and post the output as well as look at the vsphere logs

**Comment by atiniir** [comment] 2015-05-19 20:02
this is from a rhel 6.6 template, same error as with windows template

Dumping dest_folder
Folder("group-v22")
Dumping clone_spec
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    globalIPSettings: CustomizationGlobalIPSettings(  ),
    identity: CustomizationLinuxPrep(
      domain: "itlab.company.com",
      hostName: CustomizationFixedName( name: "ks-chef04" )
    )
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-163"),
    pool: ResourcePool("resgroup-1102")
  ),
  powerOn: false,
  template: false
)

**Comment by atiniir** [comment] 2015-05-19 20:33
2015-05-19T13:30:07.160-07:00 [03824 warning 'Default' opID=6627fabc-f1] [JrnlFilePersistenceProvider] Got EOF while reading file
2015-05-19T13:30:07.176-07:00 [03824 info 'VmProv' opID=6627fabc-f1] [WorkflowXAction] Starting workflow rollback
2015-05-19T13:30:07.178-07:00 [03824 info 'VmProv' opID=6627fabc-f1] [WorkflowXAction] Workflow transaction rollback done
2015-05-19T13:30:07.178-07:00 [03824 error 'commonvpxLro' opID=6627fabc-f1] [VpxLRO] Unexpected Exception: vmodl.fault.InvalidArgument
2015-05-19T13:30:07.179-07:00 [03824 info 'commonvpxLro' opID=6627fabc-f1] [VpxLRO] -- FINISH task-internal-10977107 --  -- VmprovWorkflow -- 
2015-05-19T13:30:07.179-07:00 [03824 info 'Default' opID=6627fabc-f1] [VpxLRO] -- ERROR task-internal-10977107 --  -- VmprovWorkflow: vmodl.fault.InvalidArgument:
--> Result:
--> (vmodl.fault.InvalidArgument) {
-->    dynamicType = <unset>, 
-->    faultCause = (vmodl.MethodFault) null, 
-->    invalidProperty = <unset>, 
-->    msg = "", 
--> }
--> Args:
--> 
2015-05-19T13:30:07.179-07:00 [03824 error 'Default' opID=6627fabc] (Log recursion level 2) vmodl.fault.InvalidArgument

mem>      nestedHVEnabled = <unset>, 
mem> -->          vPMCEnabled = <unset>, 
mem> -->          scheduledHardwareUpgradeInfo = (vim.vm.ScheduledHardwareUpgradeInfo) null, 
mem> -->       }, 
mem> -->       customization = (vim.vm.customization.Specification) {
mem> -->          dynamicType = <unset>, 
mem> -->          options = (vim.vm.customization.Options) null, 
mem> -->          identity = (vim.vm.customization.LinuxPrep) {
mem> -->             dynamicType = <unset>, 
mem> -->             hostName = (vim.vm.customization.FixedName) {
mem> -->                dynamicType = <unset>, 
mem> -->                name = "ks-chef04", 
mem> -->             }, 
mem> -->             domain = "itlab.ea.com", 
mem> -->             timeZone = <unset>, 
mem> -->             hwClockUTC = <unset>, 
mem> -->          }, 
mem> -->          globalIPSettings = (vim.vm.customization.GlobalIPSettings) {
mem> -->             dynamicType = <unset>, 
mem> -->          }, 
mem> -->       }, 
mem> -->       powerOn = false, 
mem> -->       snapshot = <unset>, 
mem> -->       memory = <unset>, 
mem> -->    }, 
mem> -->    name = "ks-chef05", 
mem> -->    sanitizedName = <unset>, 
mem> -->    folder = 'vim.Folder:group-v22', 
mem> -->    dstSpec = (vim.vm.ConfigSpec) null, 
mem> -->    dstVm = <unset>, 
mem> -->    tempSnapshotName = <unset>, 
mem> -->    checkpointFileName = <unset>, 
mem> -->    vAppClone = false, 
mem> --> }
mem> 2015-05-19T13:30:07.145-07:00 [03824 info 'vmprovselectDestinationImpl' opID=6627fabc-f1] Changing datastore for disk (2000) from (datastore-194) to (datastore-163)
mem> 2015-05-19T13:30:07.145-07:00 [03824 error 'vmprovvpxdVmprov' opID=6627fabc-f1] [VpxdVmprovUtil] No hosts found in compute resource domain-c1101 
mem> 2015-05-19T13:30:07.145-07:00 [03824 error 'VmProv' opID=6627fabc-f1] [Workflow] Get exception while executing action vpx.vmprov.SelectDestination: vmodl.fault.InvalidArgument

there is then a large dump of vpx.vmprov.CloneContext

**Comment by atiniir** [comment] 2015-05-19 21:30
the trouble seems to get started around here

2015-05-19T12:46:10.163-07:00 [02528 info 'vmprovselectDestinationImpl' opID=61a8e719-22] Changing datastore for disk (2000) from (datastore-194) to (datastore-163)
2015-05-19T12:46:10.163-07:00 [02528 error 'vmprovvpxdVmprov' opID=61a8e719-22] [VpxdVmprovUtil] No hosts found in compute resource domain-c1101 
2015-05-19T12:46:10.163-07:00 [02528 error 'VmProv' opID=61a8e719-22] [Workflow] Get exception while executing action vpx.vmprov.SelectDestination: vmodl.fault.InvalidArgument

I can't find a way to set the cluster or compute resource to use from the command line.  And i need to sort out which compute resource domain-c1101

**Comment by swalberg** [comment] 2015-05-19 22:47
From https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.VirtualMachine.html#clone

```
InvalidArgument: Thrown if the host cannot run this virtual machine.
```

**Comment by atiniir** [comment] 2015-05-19 22:51
that seems to make sense, however i'm not sure how i can provide a specific host or cluster to use given the current accepted parameters.

**Comment by swalberg** [comment] 2015-05-19 22:59
If we can find the parameter to add, I can add it in as a command line option (if it's not there already). `--dest_folder` also accepts resource pools. Is there a pool you could assign it to that would work?

**Comment by atiniir** [comment] 2015-05-19 23:08
--dest_folder isn't found
--dest-folder isn't finding either folders or resource pools for me atm 

also tried
--resource-pool 
--datastorecluster  
neither of those can find the related object (which i've just created)

**Comment by atiniir** [comment] 2015-05-19 23:12
aha. i've found it's selecting the 4th cluster (of 4) which indeed doesn't have any hosts. 

i'm going to see if i can move a host to it (this is a lab environment but the infra guys that manage it are afk) 

if there was a --cluster  arg that'd be super helpful atm

**Comment by atiniir** [comment] 2015-05-19 23:12
or a --host-to-use

**Comment by swalberg** [comment] 2015-05-19 23:26
We're getting somewhere! Can you post some output that lead you to this? I'll get some help from a co-worker that understands this stuff a bit better than I do, maybe we can figure this out. If it's selecting the 4th cluster then that's probably VMWare making a guess since we're not passing it in the [CloneSpec](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.CloneSpec.html).

BTW with `--resource-pool` not being able to find your cluster, what error did you get? I thought that's how it's supposed to be supplied, and perhaps [this code](https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/base_vsphere_command.rb#L192-L214) is not finding it.

**Comment by atiniir** [comment] 2015-05-19 23:41
Showing my 'math' as it were... 

i noticed in the logs before no matter what i passed the logs had: No hosts found in compute resource domain-c1101 

I looked around on the MOB and via PowerCLI and finally found "clustercomputeresource-domain-c1101" is the ID assigned to the aforementioned cluster004 

I obviously haven't used this cluster when i'm doing manual clones because I can't, it has no hosts, just like the error says :) 

after a little fast-and-loose playing with the lab i've moved a host into the cluster and now the clone command via knife works! 

*takes  a minute to really enjoy that. takes a deep breath* 

the error i got with --resource-pool is "no such pool Chef while looking for Chef"

**Comment by atiniir** [comment] 2015-05-19 23:52
confirmed find_pool isn't working well.. i added some logging: 

        puts 'pool Name'
        pp poolName

        dc = get_datacenter
        baseEntity = dc.hostFolder
        entityArray = poolName.split('/')
        entityArray.each do |entityArrItem|
          puts 'checking pool... '
          pp entityArrItem

output certainly points to something amiss 

pool Name
"Chef"
checking pool...
"Chef"
no such pool Chef while looking for Chef  

i'll poke around in the code and check what entity types are actually in play

**Comment by swalberg** [comment] 2015-05-20 03:05
So that code you're debugging is trying to find the given `poolName` off of the dc' root folder. The `entityArray` loop is trying to find it recursively: if `poolName` was something like `servers/Chef` then it would first look for `servers` then `Chef` under that. But since there are no slashes in your pool name it's the simplest case -- a container named "Chef" right off the root.

I think it would be interesting to know what `base_entity.class` is. If `Chef` is really there and it's not finding it, my guess is that it's hitting the wrong `is_a?` check, either because it's making an assumption about your environment that's not valid, or you have some config that's leading it astray. In that case it's looking for `Chef` underneath the wrong collection.

So before the loop you could do:
```
  puts "base_entity is a #{base_entity.class}"
  if base_entity.childEntity.find { |f| f.name == "Chef" }
    puts "Case 1: I found Chef as a RbVmomi::VIM::Folder"
  elsif base_entity.resourcePool.resourcePool.find { |f| f.name == "Chef" }
    puts "Case 2: I found Chef as a #{base_entity.class}"
  elsif base_entity.resourcePool.find { |f| f.name == "Chef" }
    puts "Case 3: I found Chef as a RbVmomi::VIM::ResourcePool"
  else
    puts "Case 4: This makes me sad"
  end
```

(If that crashes you might have to run each test individually, or prefix each if with something like `base_entity.respond_to? :child_entity` to make sure it supports the method you're calling. This is deep within rbvmomi, which has a strange binary config and some nasty metaprogramming)

The other possibility is that we have the wrong definition of datacenter which is why the search is off. 
https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/base_vsphere_command.rb#L192-L214 which is the place the DC is configured.

**Closed** 2016-04-27 16:39 UTC
